[alias]
build-ios = ["build", "--target", "aarch64-apple-ios"]
build-ios-sim = ["build", "--target", "aarch64-apple-ios-sim"]
build-android = ["build", "--target", "aarch64-linux-android"]

# Linker configuration settings.
[target.aarch64-apple-ios]
rustflags = [
  "-C", "link-arg=-isysroot", "-C", "link-arg=$(xcrun --sdk iphoneos --show-sdk-path)",
  "-C", "link-arg=-arch", "-C", "link-arg=arm64",
  "-C", "link-arg=-mios-version-min=10.0"
]
[target.aarch64-apple-ios-sim]
rustflags = [
  "-C", "link-arg=-isysroot", "-C", "link-arg=$(xcrun --sdk iphoneos --show-sdk-path)",
  "-C", "link-arg=-arch", "-C", "link-arg=arm64",
  "-C", "link-arg=-mios-version-min=10.0"
]

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "aarch64-linux-android-ar"

[target.armv7-linux-androideabi]
linker = "armv7-linux-androideabi21-clang"
ar = "armv7-linux-androideabi-ar"

[target.i686-linux-android]
linker = "i686-linux-android-clang"
ar = "i686-linux-android-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"
ar = "x86_64-linux-android-ar"
